version: '3.8'

services:
  auction-app:
    build: .
    container_name: auction-app-container
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge 